package io.github.kory33.guardedqueries.core.fol

import uk.ac.ox.cs.pdq.fol.Variable

/**
 * A class that manages the creation of fresh variables.
 *
 * The method `Variable.getFreshVariable()` can be used to create a fresh variable, but it
 * generates a variable that is "globally" fresh, which is not always desirable.
 *
 * This class is used to create a fresh variable that is "locally" fresh, starting from a given
 * prefix. Every time we invoke `getFreshVariable()` on an instance `context` of this class, we
 * obtain a variable that is not yet generated by `context`.
 */
class LocalVariableContext(private val variablePrefix: String) {
  private var variableCount = 0

  def getFreshVariable: Variable = {
    val newVariable = Variable.create(this.variablePrefix + this.variableCount)
    this.variableCount += 1
    newVariable
  }
}
