package io.github.kory33.guardedqueries.core.fol;

import uk.ac.ox.cs.pdq.fol.Variable;

/**
 * A class that manages the creation of fresh variables.
 * <p>
 * The method {@code Variable.getFreshVariable()} can be used to create a fresh variable,
 * but it generates a variable that is "globally" fresh, which is not always desirable.
 * <p>
 * This class is used to create a fresh variable that is "locally" fresh,
 * starting from a given prefix. Every time we invoke {@code getFreshVariable()} on an
 * instance {@code context} of this class, we obtain a variable
 * that is not yet generated by {@code context}.
 */
public class LocalVariableContext {
    private int variableCount = 0;
    private final String variablePrefix;

    public LocalVariableContext(String variablePrefix) {
        this.variablePrefix = variablePrefix;
    }

    public Variable getFreshVariable() {
        final var newVariable = Variable.create(this.variablePrefix + this.variableCount);
        this.variableCount += 1;
        return newVariable;
    }
}
