name: report

on:
  push:
    branches:
      - main

jobs:
  build-report-pdf-and-upload:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: report.tex
          working_directory: ./report
      - run: |
          mkdir -p ./_site
          cp ./report/report.pdf ./_site/report.pdf
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site
          retention-days: 30
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
